name: Compile ArmyMemo

on: 
 push:
    paths:
      - 'Latex/ArmyMemo/*'
      - '.github/workflows/Latex_ArmyMemo.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
     - name: Set up Git repository
       uses: actions/checkout@v1
     - name: Show FileSystem
       run: |
          ls -l
     - name: LaTeX compilation
       uses: dante-ev/latex-action@v0.2.0
       with:
        # The root LaTeX file to be compiled
        root_file: ArmyMemo.tex
        # The working directory for the latex compiler to be invoked
        working_directory: Latex/ArmyMemo/
        # LaTeX engine to be used
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the latex compiler
        args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
        # Install extra packages by apt-get
        # extra_system_packages: # optional
     - name: Check pdf files
       run: |
          set -e
          file Latex/ArmyMemo/ArmyMemo.pdf | grep -q ' PDF '
     - name: Create Release
       id: create_release
       uses: actions/create-release@v1.0.0
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          tag_name: ArmyMemo
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
     - name: Upload Release Asset
       id: upload-release-asset 
       uses: actions/upload-release-asset@v1.0.1
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Latex/ArmyMemo/ArmyMemo.pdf
          asset_name: ArmyMemo.pdf
          asset_content_type: application/pdf
