name: Compile Seminar

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
     - name: Set up Git repository
       uses: actions/checkout@v1
     - name: LaTeX compilation
       uses: dante-ev/latex-action@v0.2.0
       with:
        # The root LaTeX file to be compiled
        root_file: Seminar.tex
        # The working directory for the latex compiler to be invoked
        working_directory: Seminar/
        # LaTeX engine to be used
        compiler: latexmk # optional, default is latexmk
        # Extra arguments to be passed to the latex compiler
        args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
        # Install extra packages by apt-get
        # extra_system_packages: # optional
     - name: Check pdf files
       run: |
          set -e
          file test/test.pdf | grep -q ' PDF '
          file test/math.pdf | grep -q ' PDF '
          file test/biblatex.pdf | grep -q ' PDF '
          file test/minted.pdf | grep -q ' PDF '
